dev-labs-bg/dev-challenge

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/classes/category.ts
- src/app/classes/role.ts
- src/app/classes/user.ts
- src/app/components/admin/admin-categories/admin-categories.component.html
- src/app/components/admin/admin-categories/admin-categories.component.scss
- src/app/components/admin/admin-categories/admin-categories.component.ts
- src/app/components/admin/admin-categories/category-form/category-form.component.html
- src/app/components/admin/admin-categories/category-form/category-form.component.ts
- src/app/components/admin/admin-categories/category-form/category-form.service.ts
- src/app/components/admin/admin-tasks/admin-tasks.component.html
- src/app/components/admin/admin-tasks/admin-tasks.component.ts
- src/app/components/admin/admin.component.html
- src/app/components/admin/admin.component.ts
- src/app/components/header/header.component.html
- src/app/components/login/login.component.ts
- src/app/core/admin.guard.ts
- src/app/core/auth.guard.ts
- src/app/services/admin.service.ts
- src/app/services/auth.service.ts
- src/app/services/category.service.ts
- src/app/services/http.service.ts
- src/styles.scss
* Add roles to project
* Create admin panel auth guard
* Add Categories CRUD
> Feature / admin panel

- .gitignore
- src/app/config.example.ts
- src/app/services/http.service.ts
Reference env specific configs from app config file.
> Config / App General Variables

- package.json
- src/app/admin/categories/category.service.ts
- src/app/admin/categories/create.component.ts
- src/app/admin/categories/edit.component.ts
- src/app/admin/categories/list.component.ts
- src/app/app.module.ts
- src/app/shared/loading-indicator.component.ts
Implements loading indicator wrapper component.
PS: @borislav-itskov , do a `npm install` when this PR is merged`.
> Feature / Loading Indicator

- src/app/admin/assessments/exam-answer-form/exam-answer-form.component.html
- src/app/admin/assessments/exam-answer-form/exam-answer-form.component.ts
- src/app/admin/assessments/open-answer-form/open-answer-form.component.html
- src/app/admin/assessments/open-answer-form/open-answer-form.component.ts
- src/app/admin/assessments/question.service.ts
- src/app/admin/tasks/task.service.ts
- src/app/admin/tasks/tasks.component.html
- src/app/admin/tasks/tasks.component.ts
* Add missing error messages.
* Add missing loading indicators.
> Change / Loading and Errors

- src/app/todos/item.component.ts
Implements mostly the todo item UI
> Feature / Todo Item Display

- src/app/config.example.ts
- src/app/services/http.service.ts
- src/app/todos/item.component.ts
- src/app/todos/todo.ts
* Move application token to config file and remove everything from http.service
* Change Todo model so it contains task as an object rather than assigning task properties to todo model.
> Change / Dashboard Todo Status

- src/app/admin/assessments/assessment.ts
- src/app/admin/assessments/assessments.component.html
- src/app/admin/tasks/task.ts
- src/app/assessment/assessment.component.ts
- src/app/assessment/assessment.ts
- src/app/assessment/constants.ts
Refactors the assessments types / ids / constants logic.
> Refactor / Assessments Types

- src/app/register/register.component.ts
- src/app/register/steps/time-investment.component.ts
- src/app/services/auth.service.ts
* Allow an user to choose his task-category on registration
> Feature / Register choose category

- src/app/app.module.ts
- src/app/contributions/contributions.component.ts
- src/app/contributions/open-source.component.ts
- src/app/contributions/public-activity.component.ts
- src/app/contributions/side-project.component.ts
- src/app/contributions/stack-overflow.component.ts
- src/app/contributions/status.component.ts
* Refactor: Contributions to component based approach;
* Add: Award status to contributors;
> Feature / Bonus Statuses

- src/tsconfig.json
Fixes the experimental decorators annoying warning, see https://github.com/Microsoft/TypeScript/issues/8905
> Config / TSLint

- src/app/config.example.ts
- src/app/shared/one-signal-notifications.component.ts
* fix a bug where one signal crashed if user said no thanks to his notifications
> Fix / One Signal Notifcations

- src/app/admin/bonuses/bonuses.component.ts
- src/app/admin/tasks/tasks.component.html
- src/app/assessment/exam/form-item.component.ts
- src/app/assessment/micro-project/micro-project.component.ts
- src/app/todos/item.component.ts
- src/styles.scss
* Display new line on all descriptions;
> Fix / Line Breaks

- src/app/shared/audio-player.component.ts
> Config / Add Play Method to Audio Player

- src/app/shared/audio-player.component.ts
- src/app/shared/audio-recorder.component.ts
Implements a countdown for the audio answer.
> Feature / Audio Answer Countdown

- src/app/assessment/question/create.component.ts
- src/app/shared/audio-recorder.component.ts
- Fixed: subscription issue;
- Added: Upload audio loading indicator
> Config / Audio Recorder

- src/app/assessment/assessment.service.ts
- src/app/assessment/exam/create.component.ts
- src/app/assessment/exam/form-item.component.ts
- src/app/todos/todo.ts
Implements submitting exam answers and resetting exam.
> Feature / Exam Submission

- src/app/app.module.ts
- src/app/components/account-activation/account-activation.component.ts
- src/app/components/experience-block/experience-block.component.ts
- src/app/components/header/header.component.ts
- src/app/components/login/login.component.ts
- src/app/components/social/social.component.ts
- src/app/contributions/form.component.ts
- src/app/contributions/open-source.component.ts
- src/app/contributions/public-activity.component.ts
- src/app/contributions/side-project.component.ts
- src/app/contributions/stack-overflow.component.ts
- src/app/core/admin.guard.ts
- src/app/core/auth.guard.ts
- src/app/core/auth.service.ts
- src/app/core/social.guard.ts
- src/app/register/register.component.ts
- src/app/shared/one-signal-notifications.component.ts
Simply move the Authentication Service to the `./core` directory
> Config / Move the AuthService to ./core

- src/app/assessment/exam/create.component.ts
- src/app/assessment/exam/form-item.component.ts
Shuffle the exam answers, so the correct one isn't always the 4th answer. Plus, send to API the correct answer id for each question.
> Feature / Shuffle Exam Answers

- src/app/core/no-auth.guard.ts
Fixes an issue with the no-auth-guard logic.
> Bug / No Auth Guard Issue

- src/app/components/experience-block/experience-block.component.ts
- src/app/contributions/contributions.component.ts
- src/app/contributions/form.component.ts
- src/app/contributions/open-source.component.ts
- src/app/contributions/public-activity.component.ts
- src/app/contributions/side-project.component.ts
- src/app/contributions/stack-overflow.component.ts
Communicate the way bonus experience points are gained.
> General / Bonus Experience Points Copy

- src/app/register/steps/additional-info.component.ts
- src/app/register/steps/main-info.component.ts
Change log:
* Make some registration fields optional
> Feature / Registration Fields

- src/app/register/steps/main-info.component.ts
Change log:
* Check if email has already been taken on registration
> Feature/ Check taken email

- src/app/admin/categories/category.service.ts
- src/app/admin/submissions/submission.service.ts
- src/app/admin/submissions/submission.ts
- src/app/admin/tasks/tasks.component.ts
- src/app/assessment/exam/create.component.ts
- src/app/components/experience-block/experience-block.component.ts
- src/app/register/steps/time-investment.component.ts
- src/app/services/http.service.ts
- src/app/shared/user.service.ts
- src/app/todos/item.component.ts
Change log:
* add: allow only published categories for registration;
* add: hide failed todos from dashboard;
* add: remove exam assessments from submissions;
* add: updating task list now refreshes data;
* add: resetting data on experience block and other places;
* add; error message handlig;
> Fix / General Stuff

- src/app/admin/bonuses/form.component.ts
- src/app/admin/submissions/single/single.component.html
- src/app/admin/submissions/single/single.component.ts
- src/app/classes/user.ts
Change log:
* Calculate experience points for todo;
* Allow a max of 25 exp points for extra submissions;
> Feature / Experience Algorithm

- src/app/admin/submissions/single/single.component.html
- src/app/admin/submissions/single/single.component.ts
- src/app/admin/submissions/submission.ts
- src/app/admin/submissions/submissions.component.html
- src/app/admin/submissions/submissions.component.ts
- src/app/app.routing.ts
- src/app/todos/todo.service.ts
Change log:
* add: show task title on submissions;
* add: when going back from submissions, load previous category + tasks;
> Fix / Small Things

- src/app/app.routing.ts
- src/app/login/login.component.ts
Change log:
* fix: duplicate email response on taken email;
> Hotfix / Github duplicate email

- src/app/admin/submissions/single/single.component.html
- src/app/admin/submissions/single/single.component.ts
- src/app/admin/submissions/submission.service.ts
- src/app/assessment/micro-project/create.component.ts
- src/app/assessment/question/create.component.ts
Change log:
* add: reset todos data on submission approve / deny;
* add: rest submission data on new submission;
* add: confirmation for submission deny / approve;
* add: disable calls for approve / deny after hitting them first time;
> Addon / Reset Submission Data

- src/app/config.example.ts
- src/app/login/login.component.ts
- src/app/register/constants.ts
- src/app/register/register.component.ts
- src/app/register/steps/additional-info.component.ts
- src/app/register/steps/main-info.component.ts
- src/app/register/steps/time-investment.component.ts
- src/app/register/steps/verify-email.component.ts
Prerequisites:
* There's a new constant in config.ts file - github_endpoint. Open config.example.ts and copy paste it to your origin config.ts.
Change log:
* Add github button on registration
* Add back button on registration
* Make last step fields optional
* Date of birth is now Year of birth
* Add a button that opens email provider's website if in email domains array
Optional To Do ( not done ):
* Add registration steps at the top of the page.
> Feature / Registration Flow Improvements

- src/app/components/social/social.component.ts
- src/app/register/steps/additional-info.component.ts
- src/app/register/steps/time-investment.component.ts
Prerequisites:
* Github login was missing some of the functionality we added to the normal registration. This PR fixes that.
Change log:
* fix a bug with github login
> Fix/Github Registration

- package.json
See https://github.com/valor-software/ngx-bootstrap/issues/1930
> Bug / Angular 4 Template Console Warning
